baseURL = "https://tinkerbell.org/"
languageCode = "en-us"
theme = "hugo-theme-learn"
title = "Tinkerbell"
Paginate = 4

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
 author = "Packet" # add your company name
 description = "Tinkerbell, a Provisioning engine by Packet"
 github = "https://github.com/tinkerbell" # add your github profile name
 email = "hello@tinkerbell.org"
 showVisitedLinks = false
 disableBreadcrumb = false
 disableNextPrev = false
 disableLanguageSwitchingButton = true
 themeVariant = "mine"
 image = "images/social/tinkerbell-social-image.png" # relative to static
 sitename = "Tinkerbell.org"
 twitter = "@tinkerbell_oss"

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-slack'></i> <em>Community Slack</em>"
url = "/community-slack/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/tinkerbell/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-file-contract '></i> License"
url = "/license"
weight = 40

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-question-circle'></i> Support"
url = "/support"
weight = 50

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-twitter'></i> Twitter"
url = "https://twitter.com/tinkerbell_oss"
weight = 60

[[menu.homepage]]
name = "Documentation"
url = "/components"
weight = 10

[[menu.homepage]]
name = "GitHub"
url = "https://github.com/tinkerbell/"
weight = 20

[[menu.homepage]]
name = "Slack Channel"
url = "/community-slack/"
weight = 30

[[menu.homepage]]
name = "Twitter"
url = "https://twitter.com/tinkerbell_oss"
weight = 40


[[menu.tink]]
name = "Tink"
url = "https://github.com/tinkerbell/tink"
title = "Provisioning & Workflow Engine"
weight = 10

[[menu.tink]]
name = "Boots"
url = "https://github.com/tinkerbell/boots"
title = "DHCP & iPXE Server"
weight = 20

[[menu.tink]]
name = "Hegel"
url = "https://github.com/tinkerbell/hegel"
title = "Metadata Service"
weight = 30

[[menu.tink]]
name = "OSIE"
url = "https://github.com/tinkerbell/osie"
title = "OS Install Environment"
weight = 40

[[menu.tink]]
name = "PBnJ"
url = "https://github.com/tinkerbell/pbnj"
title = "Power & Boot Control Service"
weight = 50
