baseURL = "https://tinkerbell.org/"
title = "Tinkerbell - Bare Metal Automation"
languageCode = "en-us"
theme = "hugo-theme-learn"
Paginate = 4

[outputFormats]
  [outputFormats.sitemap-community]
    baseName = "sitemap-community"
    mediaType = "application/xml"
    protocol = "xml://"
  [outputFormats.sitemap-examples]
    baseName = "sitemap-examples"
    mediaType = "application/xml"
    protocol = "xml://"
  [outputFormats.sitemap-terms]
    baseName = "sitemap-terms"
    mediaType = "application/xml"
    protocol = "xml://"
  [outputFormats.sitemap-faq]
    baseName = "sitemap-faq"
    mediaType = "application/xml"
    protocol = "xml://"

[outputs]
home = [ "HTML", "RSS", "JSON", "sitemap-community", "sitemap-examples", "sitemap-terms", "sitemap-faq"]

[params]
 author = "Equinix Metal" # add your company name
 description = "Tinkerbell is an open-source bare metal provisioning engine, built for a cloud native world and maintained by the team at Equinix Metal."
 github = "https://github.com/tinkerbell" # add your github profile name
 email = "hello@tinkerbell.org"
 showVisitedLinks = false
 disableBreadcrumb = false
 disableNextPrev = false
 disableLanguageSwitchingButton = true
 themeVariant = "mine"
 image = "images/social/tinkerbell-social-image.png" # relative to static
 sitename = "Tinkerbell.org"
 twitter = "@tinkerbell_oss"
 ogtitle = "Flexible automation for bare metal"
 ogdescription = "Designed for scalable provisioning of physical hardware, Tinkerbell is both open-source and cloud native. Contributed by Equinix Metal."

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-slack'></i> <em>Community Slack</em>"
url = "/community/slack/"
weight = 10

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-github'></i> GitHub"
identifier = "ds"
url = "https://github.com/tinkerbell/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-file-contract '></i> License"
url = "/terms/license"
weight = 40

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-question-circle'></i> Support"
url = "/community/support"
weight = 50

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-twitter'></i> Twitter"
url = "https://twitter.com/tinkerbell_oss"
weight = 60

[[menu.homepage]]
identifier = "faq"
name = "FAQ's"
url = "/faq/"
weight = 1

[[menu.homepage]]
identifier = "docs"
name = "Docs"
url = "https://docs.tinkerbell.org/"
weight = 10

[[menu.homepage]]
identifier = "examples"
name = "Examples"
url = "/examples/"
weight = 15

[[menu.homepage]]
identifier = "community"
name = "Community"
url = "/community/"
weight = 20

[[menu.homepage]]
pre = "<i class='fab fa-fw fa-github'></i>"
name = "GitHub"
url = "https://github.com/tinkerbell/"
weight = 20

[[menu.homepage]]
pre = "<i class='fab fa-fw fa-slack'></i>"
name = "Slack Channel"
url = "/community/slack/"
weight = 30

[[menu.homepage]]
pre = "<i class='fab fa-fw fa-twitter'></i>"
name = "Twitter"
url = "https://twitter.com/tinkerbell_oss"
weight = 40

[[menu.homepage]]
pre = "<i class='fab fa-fw fa-youtube'></i>"
name = "Youtube"
url = "https://www.youtube.com/channel/UCTzWInTQPvzH21KHS8jrq7A"
weight = 20

[[menu.tink]]
name = "Tink"
url = "https://github.com/tinkerbell/tink"
title = "Provisioning & Workflow Engine"
weight = 10

[[menu.tink]]
name = "Boots"
url = "https://github.com/tinkerbell/boots"
title = "DHCP & iPXE Server"
weight = 20

[[menu.tink]]
name = "Hegel"
url = "https://github.com/tinkerbell/hegel"
title = "Metadata Service"
weight = 30

[[menu.tink]]
name = "OSIE"
url = "https://github.com/tinkerbell/osie"
title = "OS Install Environment"
weight = 40

[[menu.tink]]
name = "PBnJ"
url = "https://github.com/tinkerbell/pbnj"
title = "Power & Boot Control Service"
weight = 50

[[menu.footer]]
name = "Terms"
url = "/terms"
title = "Terms"
weight = 10

[[menu.footer]]
name = "License"
url = "/terms/license"
title = "License"
weight = 30

[[menu.footer]]
name = "Code of Conduct"
url = "/terms/code-of-conduct"
title = "Code of Conduct"
weight = 40

[[menu.footer]]
name = "Contributor Guide"
url = "/terms/contributor-guide"
title = "Contributor Guide"
weight = 50
