baseURL = 'https://tinkerbell.org/'
languageCode = 'en-us'
title = 'Tinkerbell'
theme = "hugo-geekdoc"

pluralizeListTitles = false

# Geekdoc required configuration
pygmentsUseClasses = true
pygmentsCodeFences = true
disablePathToLower = true

# Needed for mermaid shortcodes
[markup]
[markup.goldmark.renderer]
# Needed for mermaid shortcode or when nesting shortcodes (e.g. img within columns or tabs)
unsafe = true
hardWraps = false
xhtml = false

[markup.tableOfContents]
startLevel = 2
endLevel = 2
[markup.highlight]
anchorLineNos = false
codeFences = true
guessSyntax = false
hl_Lines = ''
hl_inline = false
lineAnchors = ''
lineNoStart = 1
lineNos = false
lineNumbersInTable = true
noClasses = true
noHl = false
style = 'tango'
tabWidth = 4

[taxonomies]
tag = "tags"

[outputs]
home = ["HTML", "RSS"]

[params]
geekdocSearch = true
author.name = "Tinkerbell Community"
description = "Tinkerbell is an open-source bare metal provisioning engine, built for a cloud native world and maintained by the Tinkerbell community."
github = "https://github.com/tinkerbell"
email = "cncf-tinkerbell-dev@lists.cncf.io"
image = "images/social/tinkerbell-social-image.png"                                                                                                                   # relative to static
sitename = "Tinkerbell.org"
ogtitle = "Flexible automation for bare metal"
ogdescription = "Designed for scalable provisioning of physical hardware, Tinkerbell is both open-source and cloud native. Contributed to the CNCF by Equinix Metal."

geekdocBreadcrumb = true
geekdocDarkModeToggle = false
geekdocDarkModeCode = false
geekdocDarkModeDim = true
geekdocLogo = "Tinkerbell-Logo-Landscape-Light.png"
geekdocOverwriteHTMLBase = false
geekdocMenuBundle = true
geekdocBackToTop = false
geekdocRepo = "https://github.com/tinkerbell/tinkerbell.org"
geekdocEditPath = "edit/main/"

[[menu.shortcuts]]
name = "<i class='fab fa-fw fa-slack'></i> <em>Slack</em>"
url = "https://cloud-native.slack.com/archives/C01SRB41GMT"
weight = 10

[[menu.shortcuts]]
name = '<i class="fa-regular fa-github"></i> GitHub'
identifier = "ds"
url = "https://github.com/tinkerbell/"
weight = 20

[[menu.shortcuts]]
name = "<i class='fas fa-fw fa-file-contract '></i> License"
url = "/terms/license"
weight = 40

[[menu.homepage]]
identifier = "docs"
name = "Docs"
url = "/docs/"
weight = 1

# [[menu.homepage]]
# identifier = "faq"
# name = "FAQ"
# url = "/faq/"
# weight = 10

[[menu.homepage]]
identifier = "community"
name = "Community"
url = "/docs/reference/community/"
weight = 20

[[menu.homepage]]
pre = '<i class="fab fa-fw fa-github"></i>'
name = "GitHub"
url = "https://github.com/tinkerbell/"
weight = 20

[[menu.homepage]]
pre = "<i class='fab fa-fw fa-slack'></i>"
name = "Slack"
url = "https://cloud-native.slack.com/archives/C01SRB41GMT"
weight = 30

[[menu.homepage]]
pre = "<i class='fab fa-fw fa-youtube'></i>"
name = "Youtube"
url = "https://www.youtube.com/channel/UCTzWInTQPvzH21KHS8jrq7A"
weight = 20

[[menu.tink]]
name = "Tink"
url = "https://github.com/tinkerbell/tink"
title = "Workflow Server, Worker, and Controller"
weight = 10

[[menu.tink]]
name = "Smee"
url = "https://github.com/tinkerbell/smee"
title = "DHCP & iPXE Server"
weight = 20

[[menu.tink]]
name = "Hegel"
url = "https://github.com/tinkerbell/hegel"
title = "Metadata Service"
weight = 30

[[menu.tink]]
name = "Rufio"
url = "https://github.com/tinkerbell/rufio"
title = "BMC Interactions"
weight = 40

[[menu.tink]]
name = "Hook"
url = "https://github.com/tinkerbell/hook"
title = "Operating System Installation Environment (OSIE)"
weight = 50

# [[menu.footer]]
# name = "Terms"
# url = "/terms"
# title = "Terms"
# weight = 10

# [[menu.footer]]
# name = "License"
# url = "/terms/license"
# title = "License"
# weight = 30

# [[menu.footer]]
# name = "Code of Conduct"
# url = "/terms/code-of-conduct"
# title = "Code of Conduct"
# weight = 40

# [[menu.footer]]
# name = "Contributor Guide"
# url = "/terms/contributor-guide"
# title = "Contributor Guide"
# weight = 50
